resources:
  - name: repo_1_docker_build_push
    type: GitRepo
    configuration:
      gitProvider: manishas_jfrog_github   # replace with your integration
      path: manishas-jfrog/jfrog-pipelines-docker-build-push    # replace with your repository name
      branches:
        include: master

  - name: build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1
      
  - name: image_pipelinedbp
    type: Image
    configuration:
      registry: demoArt
      sourceRepository: docker_local   # required if registry is Artifactory
      imageName: manisha.jfrog.io/docker-local/mydockerbase
      imageTag: latest       
      autoPull: true

pipelines:
  - name: pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: manisha.jfrog.io/docker-local/mydockerbase
          dockerImageTag: ${run_number}
          inputResources:
            - name: repo_1_docker_build_push
          integrations:
            - name: demoArt

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build
          outputResources: 
            - name: image_pipelinedbp

